class ActionKind(Enum):
    Walking = 0
    Idle = 1
    Jumping = 2
@namespace
class SpriteKind:
    follower = SpriteKind.create()
    enviroment_1 = SpriteKind.create()

def on_up_pressed():
    animation.run_image_animation(mySprite2,
        assets.animation("""
            walking up
        """),
        500,
        True)
    animation.run_image_animation(mySprite,
        assets.animation("""
            darkness walking up
        """),
        200,
        True)
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def on_on_zero(status2):
    game.over(False, effects.splatter)
statusbars.on_zero(StatusBarKind.health, on_on_zero)

def on_a_pressed():
    global projectile2
    if enemy_1.x == mySprite2.x:
        animation.run_image_animation(mySprite2,
            assets.animation("""
                explotion
            """),
            500,
            False)
        if True:
            projectile2 = sprites.create_projectile_from_sprite(assets.image("""
                explshon
            """), enemy_1, 0, 0)
            animation.run_image_animation(projectile2, assets.animation("""
                boom
            """), 500, False)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_status_reached_comparison_lte_type_percentage(status):
    music.sonar.play()
statusbars.on_status_reached(StatusBarKind.health,
    statusbars.StatusComparison.LTE,
    statusbars.ComparisonType.PERCENTAGE,
    50,
    on_status_reached_comparison_lte_type_percentage)

def on_left_pressed():
    animation.run_image_animation(mySprite2,
        assets.animation("""
            walking west
        """),
        500,
        True)
    animation.run_image_animation(mySprite,
        assets.animation("""
            waking left
        """),
        200,
        True)
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_on_overlap(sprite2, otherSprite2):
    enemy_1.follow(mySprite, 40)
    animation.run_image_animation(enemy_1,
        [img("""
                ........................
                        ....ffffff..............
                        ..ffeeeef2f.............
                        .ffeeeef222f............
                        .feeeffeeeef...cc.......
                        .ffffee2222ef.cdc.......
                        .fe222ffffe2fcddc.......
                        fffffffeeeffcddc........
                        ffe44ebf44ecddc.........
                        fee4d41fddecdc..........
                        .feee4dddedccc..........
                        ..ffee44e4dde...........
                        ...f222244ee............
                        ...f2222e2f.............
                        ...f444455f.............
                        ....ffffff..............
                        .....fff................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        .......fff..............
                        ....fffff2f.............
                        ..ffeeeee22ff...........
                        .ffeeeeee222ff..........
                        .feeeefffeeeef..........
                        .fffffeee2222ef.........
                        fffe222fffffe2f.........
                        fffffffffeeefff.....cc..
                        fefe44ebbf44eef...ccdc..
                        .fee4d4bbfddef..ccddcc..
                        ..feee4dddddfeecdddc....
                        ...f2222222eeddcdcc.....
                        ...f444445e44ddccc......
                        ...ffffffffeeee.........
                        ...fff...ff.............
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                .......ff...............
                        ....ffff2ff.............
                        ..ffeeeef2ff............
                        .ffeeeeef22ff...........
                        .feeeeffeeeef...........
                        .fffffee2222ef..........
                        fffe222ffffe2f..........
                        ffffffffeeefff..........
                        fefe44ebf44eef..........
                        .fee4d4bfddef...........
                        ..feee4dddee.c..........
                        ...f2222eeddeccccccc....
                        ...f444e44ddecddddd.....
                        ...fffffeeee.ccccc......
                        ..ffffffff...c..........
                        ..fff..ff...............
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ....ffffff..............
                        ..ffeeeef2f.............
                        .ffeeeef222f............
                        .feeeffeeeef............
                        .ffffee2222ef...........
                        .fe222ffffe2f...........
                        fffffffeeefff...........
                        ffe44ebf44eef...........
                        fee4d41fddef............
                        .feee4ddddf.............
                        ..fdde444ef.............
                        ..fdde22ccc.............
                        ...eef22cdc.............
                        ...f4444cddc............
                        ....fffffcddc...........
                        .....fff..cddc..........
                        ...........cdc..........
                        ............cc..........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """)],
        200,
        False)
    statusbar.value += -5
    pause(1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap)

def on_right_pressed():
    animation.run_image_animation(mySprite2,
        assets.animation("""
            walking east
        """),
        500,
        True)
    animation.run_image_animation(mySprite,
        assets.animation("""
            walking right
        """),
        200,
        True)
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_overlap_tile(sprite, location):
    
    def on_start_cutscene():
        story.cancel_sprite_movement(sprite)
        tiles.place_on_tile(enemy_1, tiles.get_tile_location(56, 5))
        scene.camera_shake(4, 500)
        scene.camera_follow_sprite(enemy_1)
        pause(1000)
        scene.camera_follow_sprite(mySprite)
    story.start_cutscene(on_start_cutscene)
    
    story.cancel_current_cutscene()
    tiles.replace_all_tiles(assets.tile("""
        triger
    """), sprites.castle.tile_path5)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        triger
    """),
    on_overlap_tile)

def on_down_pressed():
    animation.run_image_animation(mySprite2,
        assets.animation("""
            migamii walking down
        """),
        500,
        True)
    animation.run_image_animation(mySprite,
        assets.animation("""
            darkness walking down
        """),
        200,
        True)
controller.down.on_event(ControllerButtonEvent.PRESSED, on_down_pressed)

def on_on_overlap2(sprite3, otherSprite):
    if True:
        enemy_1.destroy(effects.fire, 1000)
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_on_overlap2)

projectile2: Sprite = None
statusbar: StatusBarSprite = None
enemy_1: Sprite = None
mySprite2: Sprite = None
mySprite: Sprite = None
mySprite = sprites.create(assets.image("""
    darkness0
"""), SpriteKind.player)
mySprite2 = sprites.create(assets.image("""
    migamii
"""), SpriteKind.follower)
mySprite3 = sprites.create(assets.image("""
    aqua
"""), SpriteKind.follower)
enemy_1 = sprites.create(img("""
        . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . .
    """),
    SpriteKind.enemy)
enemy_1.set_position(13, 123)
tiles.set_tilemap(tilemap("""
    level1
"""))
scene.set_background_color(7)
scene.camera_follow_sprite(mySprite)
controller.move_sprite(mySprite)
mySprite.set_stay_in_screen(True)
mySprite2.follow(mySprite, 85)
mySprite3.follow(mySprite, 80)
mySprite2.x += -1
mySprite3.x += 1
statusbar = statusbars.create(20, 4, StatusBarKind.health)
statusbar.attach_to_sprite(mySprite)
statusbar.set_bar_border(1, 12)
statusbar.set_label("HP")
statusbar.set_color(7, 2, 3)
statusbar.attach_to_sprite(mySprite)
statusbar.set_status_bar_flag(StatusBarFlag.SMOOTH_TRANSITION, True)
tiles.create_sprites_on_tiles(sprites.builtin.forest_tiles0, SpriteKind.enviroment_1)
tiles.cover_all_tiles(assets.tile("""
        transparency16
    """),
    sprites.castle.tile_grass1)
tiles.cover_all_tiles(sprites.builtin.forest_tiles4, sprites.castle.tile_grass3)